---
title: "O mnie"
output: html_document
---

# Welcome on our site!

My name is Alex.

## Informacje o strukturze organizacyjnej firmy:

Kapitał akcyjny 1 PLN Rada dyrektorów Funkcje kontrolne dyrektorów Brak rady nadzroczej

## Działalność spółki

## My background:

-   Licensed securities broker with investment advisory credentials no 3594, Polish Financial Supervision Authority
-   Postgraduate studies "Methods of Statistical Data Analysis", AGH University of Science and Technology in Krakow
-   Master of Laws, Lazarski University

## My skills:

-   Coding in **R**. Packages: pracma, gsl, EnvStats, gamlss.dist, VGAM, gtools, stats, forecast, zoo, FinancialMath, FinCal, actuar
-   Civil Code, Accounting Act, Construction Law Act, Commercial Companies Code, Act on Trading in Financial Instruments
-   Analiza

## My working experience:

-   Participation on the investor's side in the real estate investment process
-   Property management

## Additional information:

-   I never offer financial instruments for individuals
-   I have never been accused of committing any type of crime

## Kontakt:

You can contact me via e-mail: [janek\@example.com](mailto:janek@example.com){.email}

cd C:\Users\alekw\OneDrive\Pulpit\GitHub_strona.Rmd

# 2. Zainicjalizuj repozytorium Git w tym folderze
git init

# 3. Dodaj zdalne repozytorium GitHub
git remote add origin https://github.com/alexwer1/alexwer1.git

# 4. Dodaj wszystkie pliki w folderze do repozytorium
git add .

# 5. Zatwierdź zmiany w repozytorium z odpowiednim komunikatem
git commit -m "Initial commit"

# 6. Zmień nazwę gałęzi na 'main' (jeśli jeszcze tego nie zrobiłeś)
git branch -M main

# 7. Wypchnij zmiany do GitHub
git push -u origin main
